# Generated by Django 5.2.13 on 2026-05-02 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('p', models.FloatField()),
                ('f', models.FloatField()),
                ('grid', models.JSONField()),
                ('steps_count', models.PositiveIntegerField(default=0)),
                ('tree_density', models.FloatField(default=0.0)),
                ('fire_size_history', models.JSONField(default=dict)),
            ],
        ),
    ]
